version: "3.9"
services:
  server:
    build:
      context: ./server
      target: development
    volumes:
      - ./server/opt/app
      - /opt/app/node_modules
    ports:
      - 4000:4000
    env_file:
      - docker-compose.env
  client:
    build:
      context: ./client
      target: development
    volumes:
      - ./client:/opt/app:cached
      - /opt/app/node_modules
    ports:
      - 3000:000
    env_file:
      - docker-compose.env
